from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle, KeepTogether
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
import io
import re
from datetime import datetime

def clean_markdown_for_pdf(text: str) -> str:
    text = re.sub(r'\*\*([^\*]+)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*([^\*]+)\*', r'<i>\1</i>', text)
    text = re.sub(r'\[([^\]]+)\]\(([^\)]+)\)', r'<a href="\2" color="#2563EB">\1</a>', text)
    text = re.sub(r'&(?!amp;|lt;|gt;|quot;|#)', '&amp;', text)
    return text

def generate_pdf(topic: str, report: str) -> bytes:
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.3*inch,
        leftMargin=1.3*inch,
        topMargin=1.2*inch,
        bottomMargin=1*inch,
        title=f"Distill — {topic}",
        author="Distill",
        subject=topic
    )

    # colors
    BLACK = colors.HexColor('#0f0f0f')
    DARK = colors.HexColor('#1a1a1a')
    GRAY = colors.HexColor('#6b7280')
    LIGHT_GRAY = colors.HexColor('#f9fafb')
    BORDER = colors.HexColor('#e5e7eb')
    ACCENT = colors.HexColor('#2563EB')
    WHITE = colors.white

    styles = getSampleStyleSheet()

    # cover title
    cover_title = ParagraphStyle(
        'CoverTitle',
        fontSize=26,
        textColor=BLACK,
        spaceAfter=8,
        fontName='Helvetica-Bold',
        leading=32,
        alignment=TA_LEFT
    )

    # cover meta
    cover_meta = ParagraphStyle(
        'CoverMeta',
        fontSize=9,
        textColor=GRAY,
        spaceAfter=4,
        fontName='Helvetica',
        leading=14,
        alignment=TA_LEFT
    )

    # section heading
    section_heading = ParagraphStyle(
        'SectionHeading',
        fontSize=8,
        textColor=GRAY,
        spaceBefore=20,
        spaceAfter=6,
        fontName='Helvetica-Bold',
        leading=12,
        alignment=TA_LEFT,
        letterSpacing=1.5
    )

    # body
    body = ParagraphStyle(
        'Body',
        fontSize=10,
        textColor=DARK,
        spaceAfter=8,
        leading=17,
        fontName='Helvetica',
        alignment=TA_JUSTIFY
    )

    # bullet
    bullet = ParagraphStyle(
        'Bullet',
        fontSize=10,
        textColor=DARK,
        spaceAfter=5,
        leading=17,
        leftIndent=16,
        fontName='Helvetica',
        alignment=TA_LEFT
    )

    # source
    source = ParagraphStyle(
        'Source',
        fontSize=9,
        textColor=GRAY,
        spaceAfter=4,
        leading=14,
        leftIndent=12,
        fontName='Helvetica',
        alignment=TA_LEFT
    )

    # footer
    footer_style = ParagraphStyle(
        'Footer',
        fontSize=8,
        textColor=GRAY,
        fontName='Helvetica',
        alignment=TA_CENTER
    )

    story = []

    # cover block
    story.append(Spacer(1, 0.2*inch))

    # accent line at top
    story.append(HRFlowable(
        width="100%",
        thickness=3,
        color=ACCENT,
        spaceAfter=16
    ))

    story.append(Paragraph(topic, cover_title))
    story.append(Spacer(1, 6))

    # metadata row
    meta_text = f"Research Report &nbsp;&nbsp;·&nbsp;&nbsp; Generated by Distill &nbsp;&nbsp;·&nbsp;&nbsp; {datetime.now().strftime('%B %d, %Y')}"
    story.append(Paragraph(meta_text, cover_meta))
    story.append(Spacer(1, 4))

    story.append(HRFlowable(
        width="100%",
        thickness=0.5,
        color=BORDER,
        spaceAfter=20
    ))

    # parse report
    lines = report.split('\n')
    in_sources = False
    buffer_paragraphs = []

    for line in lines:
        line = line.strip()

        if not line:
            story.append(Spacer(1, 4))
            continue

        # skip H1 — already in cover
        if line.startswith('# '):
            continue

        elif line.startswith('## '):
            heading_text = line[3:].upper()
            in_sources = 'SOURCE' in heading_text

            story.append(Spacer(1, 8))
            story.append(HRFlowable(
                width="100%",
                thickness=0.5,
                color=BORDER,
                spaceAfter=8
            ))
            story.append(Paragraph(heading_text, section_heading))

        elif line.startswith('### '):
            subheading = ParagraphStyle(
                'SubHeading',
                fontSize=11,
                textColor=DARK,
                spaceBefore=12,
                spaceAfter=4,
                fontName='Helvetica-Bold',
                leading=16
            )
            story.append(Paragraph(line[4:], subheading))

        elif line.startswith('| '):
            # table row
            cells = [c.strip() for c in line.strip('|').split('|')]
            buffer_paragraphs.append(cells)

        elif line.startswith('|-') or line.startswith('|--'):
            # table separator — skip
            continue

        elif line.startswith('- ') or line.startswith('* '):
            content = clean_markdown_for_pdf(line[2:].strip())
            if in_sources:
                story.append(Paragraph(f"→ &nbsp;{content}", source))
            else:
                story.append(Paragraph(f"• &nbsp;&nbsp;{content}", bullet))

        elif line.startswith('http'):
            story.append(Paragraph(
                f'→ &nbsp;<a href="{line}" color="#2563EB">{line}</a>',
                source
            ))

        else:
            # flush table if any
            if buffer_paragraphs:
                table_data = []
                for i, row in enumerate(buffer_paragraphs):
                    table_data.append([Paragraph(c, body if i > 0 else ParagraphStyle('TH', fontSize=9, fontName='Helvetica-Bold', textColor=GRAY, leading=14)) for c in row])
                buffer_paragraphs = []

                if table_data:
                    col_count = max(len(r) for r in table_data)
                    col_width = (A4[0] - 2.6*inch) / col_count
                    t = Table(table_data, colWidths=[col_width]*col_count)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), LIGHT_GRAY),
                        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, -1), 9),
                        ('TOPPADDING', (0, 0), (-1, -1), 6),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                        ('LEFTPADDING', (0, 0), (-1, -1), 8),
                        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ]))
                    story.append(Spacer(1, 8))
                    story.append(t)
                    story.append(Spacer(1, 8))

            content = clean_markdown_for_pdf(line)
            story.append(Paragraph(content, body))

    # flush any remaining table
    if buffer_paragraphs:
        table_data = []
        for i, row in enumerate(buffer_paragraphs):
            table_data.append([Paragraph(c, body if i > 0 else ParagraphStyle('TH2', fontSize=9, fontName='Helvetica-Bold', textColor=GRAY, leading=14)) for c in row])

        if table_data:
            col_count = max(len(r) for r in table_data)
            col_width = (A4[0] - 2.6*inch) / col_count
            t = Table(table_data, colWidths=[col_width]*col_count)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), LIGHT_GRAY),
                ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            story.append(Spacer(1, 8))
            story.append(t)
            story.append(Spacer(1, 8))

    # footer
    story.append(Spacer(1, 0.4*inch))
    story.append(HRFlowable(
        width="100%",
        thickness=0.5,
        color=BORDER,
        spaceAfter=8
    ))
    story.append(Paragraph(
        f"Generated by Distill &nbsp;·&nbsp; distill.streamlit.app &nbsp;·&nbsp; {datetime.now().strftime('%B %d, %Y')}",
        footer_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()