from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import io
import re
from datetime import datetime

def clean_markdown_for_word(text: str) -> str:
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)
    text = re.sub(r'\*\*([^\*]+)\*\*', r'\1', text)
    text = re.sub(r'\*([^\*]+)\*', r'\1', text)
    return text

def add_horizontal_line(doc):
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), 'E5E7EB')
    pBdr.append(bottom)
    pPr.append(pBdr)
    p.paragraph_format.space_after = Pt(0)
    return p

def set_font(run, name='Calibri', size=11, bold=False, italic=False, color=None):
    run.font.name = name
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    if color:
        run.font.color.rgb = RGBColor(*color)

def generate_word(topic: str, report: str) -> bytes:
    doc = Document()

    # page margins
    for section in doc.sections:
        section.top_margin = Inches(1.2)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.3)
        section.right_margin = Inches(1.3)

    # cover — accent line simulation via colored paragraph
    cover_line = doc.add_paragraph()
    cover_run = cover_line.add_run('━' * 60)
    set_font(cover_run, size=8, color=(37, 99, 235))
    cover_line.paragraph_format.space_after = Pt(12)

    # title
    title_para = doc.add_paragraph()
    title_run = title_para.add_run(topic)
    set_font(title_run, size=24, bold=True, color=(15, 15, 15))
    title_para.paragraph_format.space_after = Pt(6)

    # meta
    meta_para = doc.add_paragraph()
    meta_run = meta_para.add_run(
        f"Research Report  ·  Generated by Distill  ·  {datetime.now().strftime('%B %d, %Y')}"
    )
    set_font(meta_run, size=9, color=(107, 114, 128))
    meta_para.paragraph_format.space_after = Pt(12)

    add_horizontal_line(doc)

    # parse report
    lines = report.split('\n')
    in_sources = False

    for line in lines:
        line = line.strip()

        if not line:
            doc.add_paragraph().paragraph_format.space_after = Pt(2)
            continue

        if line.startswith('# '):
            continue

        elif line.startswith('## '):
            heading_text = line[3:].upper()
            in_sources = 'SOURCE' in heading_text

            doc.add_paragraph().paragraph_format.space_before = Pt(4)
            add_horizontal_line(doc)

            h_para = doc.add_paragraph()
            h_run = h_para.add_run(heading_text)
            set_font(h_run, size=8, bold=True, color=(107, 114, 128))
            h_para.paragraph_format.space_after = Pt(6)
            h_para.paragraph_format.space_before = Pt(2)

        elif line.startswith('### '):
            sub_para = doc.add_paragraph()
            sub_run = sub_para.add_run(line[4:])
            set_font(sub_run, size=11, bold=True, color=(26, 26, 26))
            sub_para.paragraph_format.space_before = Pt(8)
            sub_para.paragraph_format.space_after = Pt(4)

        elif line.startswith('| '):
            cells = [clean_markdown_for_word(c.strip()) for c in line.strip('|').split('|')]
            if not any(c.startswith('-') for c in cells):
                try:
                    table = doc.tables[-1]
                except IndexError:
                    col_count = len(cells)
                    table = doc.add_table(rows=0, cols=col_count)
                    table.style = 'Table Grid'

                row = table.add_row()
                for i, cell_text in enumerate(cells):
                    if i < len(row.cells):
                        cell = row.cells[i]
                        p = cell.paragraphs[0]
                        run = p.add_run(cell_text)
                        set_font(run, size=9, color=(26, 26, 26))

        elif line.startswith('|-') or line.startswith('|--'):
            continue

        elif line.startswith('- ') or line.startswith('* '):
            content = clean_markdown_for_word(line[2:].strip())
            b_para = doc.add_paragraph(style='List Bullet')
            b_run = b_para.add_run(content)
            if in_sources:
                set_font(b_run, size=9, color=(107, 114, 128))
            else:
                set_font(b_run, size=10, color=(26, 26, 26))
            b_para.paragraph_format.space_after = Pt(3)

        else:
            content = clean_markdown_for_word(line)
            b_para = doc.add_paragraph()
            b_run = b_para.add_run(content)
            set_font(b_run, size=10, color=(26, 26, 26))
            b_para.paragraph_format.space_after = Pt(6)
            b_para.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    # footer
    doc.add_paragraph()
    add_horizontal_line(doc)
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(
        f"Generated by Distill  ·  distill.streamlit.app  ·  {datetime.now().strftime('%B %d, %Y')}"
    )
    set_font(footer_run, size=8, color=(107, 114, 128))
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()